import type { QRStyleConfig } from '@/lib/qr/generator';

export interface SystemQRTemplate {
  id: string;
  name: string;
  category: 'general' | 'memorial' | 'business' | 'pet' | 'event' | 'social';
  description: string;
  styleConfig: QRStyleConfig;
}

export const SYSTEM_QR_TEMPLATES: SystemQRTemplate[] = [
  {
    id: 'classic-black',
    name: 'Classic Black',
    category: 'general',
    description: 'Clean black and white QR code',
    styleConfig: {
      dotStyle: 'square',
      dotColor: '#000000',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'rounded-modern',
    name: 'Rounded Modern',
    category: 'general',
    description: 'Soft rounded dots with a modern feel',
    styleConfig: {
      dotStyle: 'rounded',
      dotColor: '#1a1a2e',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'elegant-memorial',
    name: 'Elegant Memorial',
    category: 'memorial',
    description: 'Muted tones with a classy dot style',
    styleConfig: {
      dotStyle: 'classy-rounded',
      dotColor: '#2c3e50',
      backgroundColor: '#faf9f6',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'H',
    },
  },
  {
    id: 'business-blue',
    name: 'Business Blue',
    category: 'business',
    description: 'Professional blue gradient',
    styleConfig: {
      dotStyle: 'rounded',
      dotGradient: {
        type: 'linear',
        rotation: 45,
        colorStops: [
          { offset: 0, color: '#0066cc' },
          { offset: 1, color: '#004499' },
        ],
      },
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'pet-tag-green',
    name: 'Pet Tag Green',
    category: 'pet',
    description: 'Friendly green for pet identification',
    styleConfig: {
      dotStyle: 'extra-rounded',
      dotColor: '#2d6a4f',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'dot',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'H',
    },
  },
  {
    id: 'event-gold',
    name: 'Event Gold',
    category: 'event',
    description: 'Warm gold gradient for celebrations',
    styleConfig: {
      dotStyle: 'dots',
      dotGradient: {
        type: 'radial',
        colorStops: [
          { offset: 0, color: '#d4a373' },
          { offset: 1, color: '#8b6914' },
        ],
      },
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'social-vibrant',
    name: 'Social Vibrant',
    category: 'social',
    description: 'Bold gradient for social media links',
    styleConfig: {
      dotStyle: 'dots',
      dotGradient: {
        type: 'linear',
        rotation: 135,
        colorStops: [
          { offset: 0, color: '#f72585' },
          { offset: 1, color: '#7209b7' },
        ],
      },
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'dot',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'restaurant-warm',
    name: 'Restaurant Warm',
    category: 'business',
    description: 'Warm colors for restaurant menus',
    styleConfig: {
      dotStyle: 'classy',
      dotColor: '#6b2737',
      backgroundColor: '#fefae0',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'card-elegant-navy',
    name: 'Card · Elegant Navy',
    category: 'memorial',
    description: 'Vertical card, navy background with gold accents',
    styleConfig: {
      dotStyle: 'classy-rounded',
      dotColor: '#23334e',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      cornerSquareColor: '#b99c65',
      cornerDotColor: '#b99c65',
      errorCorrectionLevel: 'H',
      cardLayout: 'vertical',
      cardBackgroundColor: '#23334e',
      cardTitleColor: '#f4f1ea',
      cardCaptionColor: '#d1c7bd',
      cardTitleFont: 'playfair',
      cardCaptionFont: 'garamond',
    },
  },
  {
    id: 'card-gold-celebration',
    name: 'Card · Gold Celebration',
    category: 'event',
    description: 'Horizontal card for invitations and celebrations',
    styleConfig: {
      dotStyle: 'dots',
      dotGradient: {
        type: 'radial',
        colorStops: [
          { offset: 0, color: '#d4a373' },
          { offset: 1, color: '#8b6914' },
        ],
      },
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      errorCorrectionLevel: 'M',
      cardLayout: 'horizontal',
      cardBackgroundColor: '#fbf8f1',
      cardTitleColor: '#23334e',
      cardCaptionColor: '#8b6914',
      cardTitleFont: 'playfair',
      cardCaptionFont: 'garamond',
    },
  },
  {
    id: 'card-minimal-mono',
    name: 'Card · Minimal Mono',
    category: 'general',
    description: 'Vertical card, clean black and white',
    styleConfig: {
      dotStyle: 'square',
      dotColor: '#000000',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      errorCorrectionLevel: 'M',
      cardLayout: 'vertical',
      cardBackgroundColor: '#FFFFFF',
      cardTitleColor: '#000000',
      cardCaptionColor: '#6b7280',
      cardTitleFont: 'inter',
      cardCaptionFont: 'inter',
    },
  },
  {
    id: 'card-business-corporate',
    name: 'Card · Business Corporate',
    category: 'business',
    description: 'Horizontal card for business cards and storefronts',
    styleConfig: {
      dotStyle: 'rounded',
      dotColor: '#0a2540',
      backgroundColor: '#FFFFFF',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      cornerSquareColor: '#0066cc',
      cornerDotColor: '#0066cc',
      errorCorrectionLevel: 'M',
      cardLayout: 'horizontal',
      cardBackgroundColor: '#FFFFFF',
      cardTitleColor: '#0a2540',
      cardCaptionColor: '#4a5568',
      cardTitleFont: 'montserrat',
      cardCaptionFont: 'inter',
    },
  },
];
